export const ASSIGNED_ROOM_REQUEST = "ASSIGNED_ROOM_REQUEST";
export const ASSIGNED_ROOM_SUCCESS = "ASSIGNED_ROOM_SUCCESS";
export const ASSIGNED_ROOM_FAIL = "ASSIGNED_ROOM_FAIL";

export const ASSIGNED_USERNAME_REQUEST = "ASSIGNED_USERNAME_REQUEST";
export const ASSIGNED_USERNAME_SUCCESS = "ASSIGNED_USERNAME_SUCCESS";
export const ASSIGNED_USERNAME_FAIL = "ASSIGNED_USERNAME_FAIL";

export const PEOPLE_LIST_REQUEST = "PEOPLE_LIST_REQUEST";
export const PEOPLE_LIST_SUCCESS = "PEOPLE_LIST_SUCCESS";
export const PEOPLE_LIST_FAIL = "PEOPLE_LIST_FAIL";

export const MESSAGE_SENDED_REQUEST = "MESSAGE_SENDED_REQUEST";
export const MESSAGE_SENDED_SUCCESS = "MESSAGE_SENDED_SUCCESS";
export const MESSAGE_SENDED_FAIL = "MESSAGE_SENDED_FAIL";
